# Generated by Django 4.0.5 on 2022-07-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1990-01-01'),
            preserve_default=False,
        ),
    ]
